import numpy as np
import tensorflow as tf
from tensorflow import keras
import os

# 1. Synthetic dataset generator for baseline electrical load features:
# Features: [v_rms, i_rms, p_act, pf, crest_factor, form_factor]
def generate_synthetic_data(samples=2000):
    X = []
    y = []

    for _ in range(samples):
        if np.random.rand() > 0.5:
            # Normal operational profiles (Label 0: Safe)
            v_rms = np.random.uniform(215.0, 235.0)
            i_rms = np.random.uniform(0.5, 10.0)
            pf = np.random.uniform(0.85, 0.99)
            p_act = v_rms * i_rms * pf
            cf = np.random.uniform(1.35, 1.55)      # Normal sine wave crest factor ~ 1.414
            ff = np.random.uniform(1.05, 1.15)      # Normal sine wave form factor ~ 1.11
            label = 0
        else:
            # Anomaly profiles (Arcing / Degradation / Spikes) (Label 1: Fault)
            v_rms = np.random.uniform(170.0, 260.0)
            i_rms = np.random.uniform(0.1, 16.0)
            pf = np.random.uniform(0.20, 0.75)
            p_act = v_rms * i_rms * pf
            cf = np.random.uniform(2.2, 5.0)        # High transient crest factor
            ff = np.random.uniform(1.3, 2.0)        # Severe harmonic distortion
            label = 1

        X.append([v_rms, i_rms, p_act, pf, cf, ff])
        y.append(label)

    return np.array(X, dtype=np.float32), np.array(y, dtype=np.int32)

print("[INFO] Generating synthetic physical telemetry dataset...")
X_train, y_train = generate_synthetic_data(4000)

# 2. Lightweight Edge Neural Network Architecture (Input shape = 6)
model = keras.Sequential([
    keras.layers.Input(shape=(6,)), # FIXED: 6 Input features
    keras.layers.Dense(12, activation="relu"),
    keras.layers.Dense(8, activation="relu"),
    keras.layers.Dense(2, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("[INFO] Training edge anomaly detection model...")
model.fit(X_train, y_train, epochs=25, batch_size=32, verbose=1)

# 3. Post-Training Quantization (INT8) for Arduino / TinyML
def representative_data_gen():
    for i in range(200):
        yield [X_train[i:i+1]]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_quant_model = converter.convert()

os.makedirs("models", exist_ok=True)
tflite_path = "models/model.tflite"
with open(tflite_path, "wb") as f:
    f.write(tflite_quant_model)

print(f"[SUCCESS] Quantized TFLite model exported: {tflite_path} ({len(tflite_quant_model)} bytes)")

# 4. Generate C Header byte array (model_data.h) for Arduino integration
header_path = "models/model_data.h"
with open(header_path, "w") as f:
    f.write("// Auto-generated by train_model.py - VoltTrace Edge TinyML Model\n")
    f.write("#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n")
    f.write(f"const unsigned int g_model_len = {len(tflite_quant_model)};\n")
    f.write("const unsigned char g_model[] __attribute__((aligned(4))) = {\n  ")
    for i, byte in enumerate(tflite_quant_model):
        f.write(f"0x{byte:02x}, ")
        if (i + 1) % 12 == 0:
            f.write("\n  ")
    f.write("\n};\n\n#endif // MODEL_DATA_H\n")

print(f"[SUCCESS] C Header exported for Arduino: {header_path}")
